CREATE TABLE hives (
    id text PRIMARY KEY,
    owner_id text,
    name text,
    bee_count integer NOT NULL DEFAULT 0,
    health integer NOT NULL DEFAULT 100,
    honey_production numeric(14, 3) NOT NULL DEFAULT 0,
    reserves integer NOT NULL DEFAULT 0,
    queen_age_days integer NOT NULL DEFAULT 0,
    queen_genetic_quality integer NOT NULL DEFAULT 0,
    lat double precision NOT NULL DEFAULT 0,
    lng double precision NOT NULL DEFAULT 0,
    hex_id text,
    site_id text,
    elevation_meters integer NOT NULL DEFAULT -1,
    flora_type text,
    honey_stocks_json text,
    super_count integer NOT NULL DEFAULT 0,
    population_state_json text,
    varroa_pct numeric(8, 3) NOT NULL DEFAULT 0,
    varroa_treatment_days_remaining integer NOT NULL DEFAULT 0,
    varroa_rebound_days_remaining integer NOT NULL DEFAULT 0,
    last_health_sim_day_key integer NOT NULL DEFAULT 0,
    first_production_day_key integer NOT NULL DEFAULT 0,
    last_summary_day_key integer NOT NULL DEFAULT 0,
    last_summary_honey_kg numeric(14, 3) NOT NULL DEFAULT 0,
    last_summary_delta_bees integer NOT NULL DEFAULT 0,
    last_summary_delta_health integer NOT NULL DEFAULT 0,
    last_summary_delta_varroa numeric(8, 3) NOT NULL DEFAULT 0,
    last_summary_worker_deaths integer NOT NULL DEFAULT 0,
    last_summary_worker_emergences integer NOT NULL DEFAULT 0,
    last_summary_eggs_laid integer NOT NULL DEFAULT 0,
    last_summary_swarmed boolean NOT NULL DEFAULT false,
    feed_honey_bonus_end_day_key_exclusive integer NOT NULL DEFAULT 0,
    feed_honey_bonus_multiplier numeric(8, 3) NOT NULL DEFAULT 1,
    feed_brood_bonus_end_day_key_exclusive integer NOT NULL DEFAULT 0,
    feed_brood_bonus_multiplier numeric(8, 3) NOT NULL DEFAULT 1,
    transhumance_arrives_day_key integer NOT NULL DEFAULT 0,
    pending_contract_hex_id text,
    pending_contract_day_key integer NOT NULL DEFAULT 0,
    contract_id text,
    contract_origin_hex_id text,
    contract_origin_flora text,
    contract_origin_lat double precision NOT NULL DEFAULT 0,
    contract_origin_lng double precision NOT NULL DEFAULT 0,
    in_warehouse boolean NOT NULL DEFAULT false,
    return_to_warehouse boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX hives_owner_idx ON hives (owner_id);
CREATE INDEX hives_hex_idx ON hives (hex_id);
